@url=http://localhost:4400/api/

### 注册
POST {{url}}register
Content-Type: application/json; charset=utf-8

{
  "phone": "1",
  "password": "1"
}

### 登录
POST {{url}}login
Content-Type: application/json; charset=utf-8

{
  "phone": "18538300839",
  "password": "123456"
}

### 使用token
GET {{url}}userinfo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkZGY0NTA0Mjk3NDg0MzdkODZhZGViMyIsImlhdCI6MTU3NDkxNzcyNX0.ji4R08Kn2hmfOp0xFIDmpYYtZvz_Ll2Q4rcfttli7rs

###
GET {{url}}all